---
- import_tasks: roles/homeshick/tasks/clone_castle.yml
  vars:
    castles: "{{ homeshick_castles | default([]) }}"
  tags:
    - dotfiles

- import_tasks: roles/homeshick/tasks/link_dotfiles.yml
  vars:
    castles: ""
  tags:
    - dotfiles
