---
- name: Ensure python2 is installed.
  homebrew:
    name: "{{ item }}"
  with_items:
    - python@2
  tags:
    - python
    - python2

- name: Ensure basic pip2 pkgs are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(omit) }}"
    executable: pip2
  with_items:
    - name: pip
      state: latest
    - pipenv
  tags:
    - python
    - python2
