---

gem_user_install: yes

#
# - <gem-name>
# or
# - name: <gem-name>
#   version: <version>
#   state: <present|absent|latest>
#
ruby_gems:
  - name: asciidoctor
    state: latest
  - bundler
  - name: kramdown
    state: latest
