---

- name: Ensure gems are installed.
  gem:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user_install: "{{ gem_user_install | default(omit) }}"
  with_items: "{{ ruby_gems | default([]) }}"
  tags:
    - ruby
    - gems
