---
- import_tasks: roles/mac/homebrew/tasks/brew.yml
  vars:
    pkgs:
      - name: doxygen
      - name: graphviz
      - name: pandoc
  tags:
    - documentation

- import_tasks: roles/mac/mas/tasks/mas.yml
  vars:
    apps:
      - appid: "448925439"
        name: Marked
  tags:
    - documentation

- import_tasks: roles/ruby/tasks/gem.yml
  vars:
    gems:
      - asciidoctor
      - kramdown
      - pygments.rb
  tags:
    - documentation

- import_tasks: roles/python3/tasks/pip.yml
  vars:
    pkgs:
      - Pygments
      - Sphinx
  tags:
    - documentation
