---
- name: Ensure python3 is installed.
  homebrew:
    name: "{{ item }}"
  with_items:
    - python
  tags:
    - python
    - python3

- import_tasks: roles/python3/tasks/pip.yml
  vars:
    pkgs:
      - name: pip
        state: latest
      - pipenv
  tags:
    - python
    - python3
