---

- name: Ensure homebrew repositories are taped.
  homebrew_tap: tap={{ item }}
  with_items: "{{ homebrew_taps | default([]) }}"
  tags:
    - homebrew

- include_tasks: brew.yml
  with_dict: "{{ homebrew_packages }}"
  loop_control:
    loop_var: group
  tags:
    - homebrew

- name: Ensure homebrew cask packages are installed.
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ homebrew_cask_apps | default([]) }}"
  tags:
    - homebrew
    - cask
