---
- name: Ensure homebrew pkgs are installed.
  homebrew:
    name: "{{ item.1.name | default(item.1) }}"
    state: "{{ item.1.state | default(omit) }}"
    install_options: "{{ item.1.options | default(omit) }}"
  with_subelements:
    - "{{ homebrew_packages | default([]) }}"
    - pkgs
  tags:
    - homebrew

- name: Ensure homebrew cask packages are installed.
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ homebrew_cask_apps | default([]) }}"
  tags:
    - homebrew
    - cask
